# openIronSDA Funding Substrate

# These are supported funding model platforms
# Sovereign Sponsorship is authorized for the research of the 7 Navigation Routes.

custom: ["https://donate.stripe.com/00w7sK53o40z21r6hm0co00"] # Replace with your official openIronSDA Stripe checkout/payment link
